name: Fraud Detection CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Run Tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest test/test_api.py -v

  # Build Docker Image (only if tests pass)
  build:
    runs-on: ubuntu-latest
    needs: test  # waits for test job to pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.riya7737 }}
          password: ${{ secrets.November2005 }}

      - name: Build and Push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ secrets.riya7737 }}/fraud-detection-api:latest

      - name: Build and Push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: ${{ secrets.riya7737 }}/fraud-detection-frontend:latest